# Generated by Django 3.2.25 on 2026-02-26 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='additional_data',
            field=models.TextField(blank=True, default='{}', help_text='Additional metadata'),
        ),
        migrations.AddField(
            model_name='review',
            name='image_url',
            field=models.TextField(blank=True, help_text='Single image URL (legacy)'),
        ),
    ]
